# Generated by Django 5.1.4 on 2024-12-08 00:36

import empleado_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado_app', '0002_alter_asignacion_fecha_asignacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='apellido',
            field=models.CharField(max_length=30, validators=[empleado_app.validators.validar_solo_letras]),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(max_length=30, validators=[empleado_app.validators.validar_solo_letras]),
        ),
    ]
