# Generated by Django 5.1.4 on 2024-12-08 00:41

import empleado_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado_app', '0003_alter_empleado_apellido_alter_empleado_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='correo',
            field=models.EmailField(max_length=254, unique=True, validators=[empleado_app.validators.validar_dominio_correo]),
        ),
    ]
